---
- name: Install Apache Tomcat10 using ansible
  hosts: webserver
  become: true
  tasks:
    - name: Create a Tomcat User
      user:
        name: tomcat

    - name: Create a Tomcat Group
      group:
        name: tomcat

    - name: Install JAVA
      yum:
        name: java-1.8.0-openjdk
        state: present


    - name: Create a Tomcat Directory
      file:
        path: /opt/tomcat10
        owner: tomcat
        group: tomcat
        mode: 755
        recurse: yes

    - name: download & unarchive tomcat10
      unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
        dest: /opt/tomcat10
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Change ownership of tomcat directory
      file:
        path: /opt/tomcat10
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory
    - name: Stop Tomcat
      command: /opt/tomcat10/bin/shutdown.sh
    - name: Delete old war
      command: rm -rf /opt/tomcat10/webapps/DevOpsApp*
    - name: Copy the war file
      copy:
        src: /var/lib/jenkins/workspace/Ansible-pipeline/target/DevOpsApp.war
        dest: /opt/tomcat10/webapps/
    - name: Start and Enable Tomcat 10 on sever
      shell: nohup /opt/tomcat10/bin/startup.sh &

